from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, TYPE_CHECKING, Union

from uta.testgen.project_summary.constants import (
    COMPILE_FACTS_FILENAME,
    CONTEXT_SUMMARY_FILENAME,
    REPO_SUMMARY_FILENAME,
    TEST_GUIDANCE_FILENAME,
    UTA_GENERATED_MARKER,
)
from uta.testgen.project_summary.guidance import (
    _extract_pom_coords,
    _list_modules,
    _read_text,
)

if TYPE_CHECKING:
    from uta.language.java.parse.models import CodeGraph


def _graph_stats(graph: "CodeGraph") -> Dict[str, Any]:
    kinds = Counter(n.kind for n in graph.nodes.values())
    packages: Counter[str] = Counter()
    for fqn, node in graph.nodes.items():
        if node.kind != "class":
            continue
        parts = fqn.split(".")
        if len(parts) >= 3:
            packages[".".join(parts[:3])] += 1
        elif len(parts) == 2:
            packages[parts[0]] += 1
    top_pkgs = packages.most_common(20)
    annos: Counter[str] = Counter()
    for node in graph.nodes.values():
        if node.kind != "class":
            continue
        for a in node.metadata.get("annotations", []) or []:
            annos[a] += 1
    top_annos = annos.most_common(15)
    return {
        "nodes_by_kind": dict(kinds),
        "top_packages": top_pkgs,
        "top_class_annotations": top_annos,
    }


def _build_context_summary_markdown(
    repo_path: str,
    graph: "CodeGraph",
    module: Optional[str],
) -> str:
    repo = Path(repo_path)
    lines: List[str] = [
        "# UTA project summary (machine-generated)",
        "",
        "Read this file for Maven layout and coarse graph statistics before writing tests.",
        "",
        f"- Repository root: `{repo.resolve()}`",
        f"- Maven module filter: `{module or '(all under scan path)'}`",
        "",
        "## Maven",
        "",
    ]
    root_pom = repo / "pom.xml"
    if root_pom.exists():
        coords = _extract_pom_coords(_read_text(root_pom))
        for k, v in coords.items():
            lines.append(f"- **{k}**: `{v}`")
        lines.append("")
        mods = _list_modules(repo, module)
        if mods:
            lines.append("### Modules (from root POM or CLI `--module`)")
            for m in mods:
                lines.append(f"- `{m}`")
            lines.append("")
    else:
        lines.append("_No root pom.xml found._")
        lines.append("")

    stats = _graph_stats(graph)
    lines.append("## Graph overview (parsed Java)")
    lines.append("")
    nbk = stats["nodes_by_kind"]
    for key in ("class", "interface", "method", "field"):
        if key in nbk:
            lines.append(f"- **{key}** count: {nbk[key]}")
    lines.append("")
    lines.append("### Top package prefixes (by class count)")
    for pkg, c in stats["top_packages"]:
        lines.append(f"- `{pkg}` — {c} classes")
    lines.append("")
    lines.append("### Frequent class-level annotations")
    for a, c in stats["top_class_annotations"]:
        lines.append(f"- `@{a}` — {c}")
    lines.append("")
    lines.append("## Related UTA context files")
    lines.append("")
    lines.append("Same directory as this file:")
    lines.append("- `class_map.md`, `dependency_map.md`, `process_flows.md`, `call_graph.md`")
    lines.append("")
    return "\n".join(lines)


def _build_repo_summary_markdown(
    repo_path: str,
    graph: "CodeGraph",
    module: Optional[str],
) -> str:
    stats = _graph_stats(graph)
    n_classes = stats["nodes_by_kind"].get("class", 0)
    lines = [
        UTA_GENERATED_MARKER,
        "",
        "# Project overview (UTA)",
        "",
        "This file was generated by the Unit Test Agent. Replace or edit it to document",
        "architecture, domain vocabulary, and test conventions for your team.",
        "",
        f"**Module scope**: `{module or 'default scan path'}`",
        f"**Classes in graph**: {n_classes}",
        "",
        "For structured stats and package breakdown, read:",
        f"`{Path(repo_path) / '.uta_cache' / 'context' / CONTEXT_SUMMARY_FILENAME}`",
        "",
        "## Maven coordinates (root `pom.xml`, best-effort)",
        "",
    ]
    root_pom = Path(repo_path) / "pom.xml"
    if root_pom.exists():
        coords = _extract_pom_coords(_read_text(root_pom))
        if coords:
            lines.append(" | ".join(f"**{k}**: `{v}`" for k, v in coords.items()))
        else:
            lines.append("_Could not parse coordinates._")
    else:
        lines.append("_No root pom.xml._")
    lines.append("")
    return "\n".join(lines)


def sync_project_summaries(
    repo_path: str,
    graph: "CodeGraph",
    module: Optional[str],
    *,
    language: str = "java",
    max_files: int = 500,
) -> Dict[str, str]:
    """Write ``project_summary.md`` under context; create or refresh ``.uta_summary.md`` when safe."""
    from uta.testgen.project_summary import make_project_summary_provider

    provider = make_project_summary_provider(
        language,
        repo_path,
        graph=graph,
        module=module,
        max_files=max_files,
    )
    return provider.sync().as_dict()


def prompt_template_paths(repo_path: str, context_dir: Union[str, Path]) -> Dict[str, Any]:
    """Template kwargs for ``generate_test.txt`` (absolute paths, existence flag)."""
    repo = Path(repo_path)
    ctx = Path(context_dir)
    rs = repo / REPO_SUMMARY_FILENAME
    cs = ctx / CONTEXT_SUMMARY_FILENAME
    tg = ctx / TEST_GUIDANCE_FILENAME
    cf = ctx / COMPILE_FACTS_FILENAME
    return {
        "repo_summary_abs": str(rs.resolve()),
        "context_summary_abs": str(cs.resolve()),
        "test_guidance_abs": str(tg.resolve()),
        "compile_facts_abs": str(cf.resolve()),
        "compile_facts_exists": cf.exists() and cf.stat().st_size > 10,
        "test_guidance_exists": tg.exists() and tg.stat().st_size > 10,
        "repo_summary_exists": rs.exists() and rs.stat().st_size > 10,
    }
