"""Language-neutral engine contracts for UTA workflows."""

from uta.engine.batch import BatchGenerationRequest, BatchGenerationResult, BatchGenerator
from uta.engine.context import ContextProvider, ContextQuery, make_context_provider
from uta.engine.enforcement import EnforcementCore, ValidationVerdict
from uta.engine.languages import (
    AmbiguousLanguageError,
    BackendRegistry,
    DetectionSignal,
    GeneratedTestPolicy,
    LanguageAdapter,
    LanguageCapabilities,
    LanguageDecision,
    PromptBundle,
    RawTargetSelection,
    UnsupportedLanguageError,
    default_registry,
    normalize_targets,
    resolve_language,
)
from uta.engine.learning import TargetLearningKey
from uta.engine.parse import (
    ParsedCallable,
    ParsedImport,
    ParseDiagnostic,
    ParseProjectRequest,
    ParseProjectResult,
    ParseProvider,
    make_parse_provider,
)
from uta.engine.project_summary import ProjectSummaryArtifacts, ProjectSummaryProvider, make_project_summary_provider
from uta.engine.scoring import TargetScoreResult, TargetScorer, TargetScorerRegistry
from uta.engine.targets import TargetIdentity, TargetRef
from uta.engine.validation import (
    BreadthResult,
    BreadthVerdict,
    FeasibilityResult,
    FeasibilityVerdict,
    PlanCallable,
    PlanContext,
    PlanContextExtractor,
    PlanContextExtractorRegistry,
    coerce_plan_context,
    default_plan_context_registry,
    extract_planned_methods_from_plan,
    validate_plan_breadth,
    validate_plan_feasibility,
)
from uta.engine.verification import VerificationResult, VerificationRunner, VerificationRunnerRegistry
from uta.engine.wave_assigner import MethodWave, assign_waves, assign_waves_from_context, format_wave_table

__all__ = [
    "AmbiguousLanguageError",
    "BackendRegistry",
    "BatchGenerationRequest",
    "BatchGenerationResult",
    "BatchGenerator",
    "BreadthResult",
    "BreadthVerdict",
    "ContextProvider",
    "ContextQuery",
    "DetectionSignal",
    "EnforcementCore",
    "FeasibilityResult",
    "FeasibilityVerdict",
    "GeneratedTestPolicy",
    "LanguageAdapter",
    "LanguageCapabilities",
    "LanguageDecision",
    "MethodWave",
    "ParsedCallable",
    "ParsedImport",
    "ParseDiagnostic",
    "ParseProjectRequest",
    "ParseProjectResult",
    "ParseProvider",
    "PlanCallable",
    "PlanContext",
    "PlanContextExtractor",
    "PlanContextExtractorRegistry",
    "ProjectSummaryArtifacts",
    "ProjectSummaryProvider",
    "PromptBundle",
    "RawTargetSelection",
    "TargetLearningKey",
    "TargetIdentity",
    "TargetRef",
    "TargetScoreResult",
    "TargetScorer",
    "TargetScorerRegistry",
    "UnsupportedLanguageError",
    "ValidationVerdict",
    "VerificationResult",
    "VerificationRunner",
    "VerificationRunnerRegistry",
    "coerce_plan_context",
    "default_registry",
    "default_plan_context_registry",
    "extract_planned_methods_from_plan",
    "assign_waves",
    "assign_waves_from_context",
    "make_context_provider",
    "make_parse_provider",
    "make_project_summary_provider",
    "normalize_targets",
    "resolve_language",
    "format_wave_table",
    "validate_plan_breadth",
    "validate_plan_feasibility",
]
