from pathlib import Path

import pytest

from uta.testgen.batch import BatchGenerationRequest
from uta.shared.languages import RawTargetSelection, default_registry
from uta.shared.targets import TargetRef
from uta.testgen.prompts.loader import render_prompt_split
from uta.language.python.batch import (
    PythonBatchGenerator,
    render_generated_test_file,
    run_python_batch_generation,
    write_generated_test_file,
)
from uta.language.python.verification.generation import (
    validate_generated_test_import_contract,
)
from uta.language.python.test_selection import (
    discover_strict_python_test_candidates,
    generated_test_path,
    select_python_test_destination,
)


def test_public_python_batch_api_preserves_quality_mode(tmp_path, monkeypatch):
    captured = {}
    target = TargetRef(
        language="python",
        target_id="pkg/router.py",
        display_name="pkg/router.py",
    )

    def capture_request(self, request):
        captured["request"] = request
        from uta.language.python.generation import PythonBatchGenerationResult

        return PythonBatchGenerationResult(results={})

    monkeypatch.setattr(PythonBatchGenerator, "run", capture_request)

    run_python_batch_generation(
        repo_path=tmp_path,
        targets=[target],
        quality_mode="ci_incremental",
    )

    assert captured["request"].quality_mode == "ci_incremental"


def test_python_prompt_bundle_is_language_owned():
    registry = default_registry()

    java_bundle = registry.prompt_bundle("java")
    python_bundle = registry.prompt_bundle("python")

    assert java_bundle.plan == "plan_tests"
    assert java_bundle.generate == "generate_test"
    assert python_bundle.plan is None  # Python has no plan stage
    assert python_bundle.generate == "python_generate_test"
    assert python_bundle.fix_compile == "python_fix_compile"
    assert python_bundle.fix_coverage == "python_fix_coverage"
    assert python_bundle.fix_mutations == "python_fix_mutations"


def test_python_generated_test_path_is_deterministic_under_uta_generated():
    target = default_registry().adapter_for("python").normalize_target(
        RawTargetSelection(target="jobs/app/ad_measure.py::parse_fee_rules")
    )

    assert generated_test_path(target) == "tests/uta_generated/test_jobs_app_ad_measure.py"
    assert generated_test_path(target) == generated_test_path(target)


def test_python_generated_test_writer_refuses_non_uta_owned_file(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    target = default_registry().adapter_for("python").normalize_target(RawTargetSelection(target="jobs/forecast.py"))
    existing = repo / generated_test_path(target)
    existing.parent.mkdir(parents=True)
    existing.write_text("def test_existing():\n    pass\n", encoding="utf-8")

    with pytest.raises(ValueError, match="not UTA-owned"):
        write_generated_test_file(repo, target, "def test_new():\n    pass\n")


def test_python_generated_test_writer_updates_uta_owned_file(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    target = default_registry().adapter_for("python").normalize_target(
        RawTargetSelection(target="jobs/forecast.py::forecast_for_store")
    )

    first = render_generated_test_file(target, body="def test_first():\n    assert True\n")
    second = render_generated_test_file(target, body="def test_second():\n    assert True\n")
    path = write_generated_test_file(repo, target, first)
    same_path = write_generated_test_file(repo, target, second)

    assert same_path == path
    text = path.read_text(encoding="utf-8")
    assert "UTA_TARGET_ID: pysymbol:jobs/forecast.py::forecast_for_store" in text
    assert "def test_second" in text
    assert "def test_first" not in text


def test_python_generated_test_writer_wraps_raw_body_with_ownership_header(tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    target = default_registry().adapter_for("python").normalize_target(RawTargetSelection(target="jobs/forecast.py"))

    path = write_generated_test_file(repo, target, "def test_raw_body():\n    assert True\n")

    text = path.read_text(encoding="utf-8")
    assert text.startswith("# Generated by UTA. Safe to update.")
    assert "UTA_TARGET_ID: pyfile:jobs/forecast.py" in text
    assert "def test_raw_body" in text


def test_python_verifier_rejects_synthetic_loader_import_even_if_runner_would_pass(tmp_path):
    repo = tmp_path / "repo"
    source = repo / "pipecat" / "router" / "router.py"
    source.parent.mkdir(parents=True)
    source.write_text("class RoutingProcessor:\n    pass\n", encoding="utf-8")
    target = default_registry().adapter_for("python").normalize_target(
        RawTargetSelection(target="pipecat/router/router.py")
    )
    test_path = write_generated_test_file(
        repo,
        target,
        "from _router_loader import TARGET_MODULE\n\n"
        "def test_router_loader_contract():\n"
        "    assert TARGET_MODULE\n",
    )

    error = validate_generated_test_import_contract(test_path)

    assert "_router_loader" in error


def test_python_verifier_rejects_file_loader_import_pattern(tmp_path):
    repo = tmp_path / "repo"
    source = repo / "jobs" / "forecast.py"
    source.parent.mkdir(parents=True)
    source.write_text("def forecast():\n    return 1\n", encoding="utf-8")
    target = default_registry().adapter_for("python").normalize_target(RawTargetSelection(target="jobs/forecast.py"))
    test_path = write_generated_test_file(
        repo,
        target,
        "import importlib.util\n\n"
        "def test_file_loader_contract():\n"
        "    assert importlib.util.spec_from_file_location('jobs.forecast', 'jobs/forecast.py')\n",
    )

    error = validate_generated_test_import_contract(test_path)

    assert "spec_from_file_location" in error


def test_python_verifier_rejects_generated_test_that_mutates_verifier_config(tmp_path):
    repo = tmp_path / "repo"
    source = repo / "pipecat" / "knowledge_retrieval" / "store.py"
    source.parent.mkdir(parents=True)
    source.write_text("def load_store():\n    return 'ok'\n", encoding="utf-8")
    target = default_registry().adapter_for("python").normalize_target(
        RawTargetSelection(target="pipecat/knowledge_retrieval/store.py")
    )
    test_path = write_generated_test_file(
        repo,
        target,
        "from pathlib import Path\n\n"
        "REPO_ROOT = Path.cwd()\n\n"
        "def _ensure_mutmut_targets_active_file():\n"
        "    sandbox_tests = REPO_ROOT / 'mutants' / 'pipecat' / 'tests'\n"
        "    sandbox_tests.mkdir(parents=True, exist_ok=True)\n"
        "    (sandbox_tests / 'conftest.py').write_text('')\n"
        "    pyproject = REPO_ROOT / 'pyproject.toml'\n"
        "    pyproject.write_text('[tool.mutmut]\\n')\n\n"
        "_ensure_mutmut_targets_active_file()\n\n"
        "def test_store_contract():\n"
        "    assert True\n",
    )

    error = validate_generated_test_import_contract(test_path)

    assert "pyproject.toml" in error
    assert "mutants/" in error


def test_python_generation_prompt_renders_context_and_import_safety(tmp_path):
    context_md = tmp_path / "forecast.context.md"
    context_md.write_text("# Python Target Context\n", encoding="utf-8")
    context_json = tmp_path / "forecast.json"
    context_json.write_text("{}", encoding="utf-8")

    stable, volatile = render_prompt_split(
        "python_generate_test",
        target_id="pysymbol:jobs/forecast.py::forecast_for_store",
        display_name="jobs/forecast.py::forecast_for_store",
        source_path="jobs/forecast.py",
        canonical_module="jobs.forecast",
        symbol="forecast_for_store",
        generated_test_path="tests/uta_generated/test_jobs_forecast.py",
        context_abs=str(context_md),
        context_json_abs=str(context_json),
        index_query_command="uta query-index --repo . --language python --target jobs/forecast.py::forecast_for_store --json-output",
        syntax_version="python3",
        parser_backend="tree_sitter",
        side_effect_hints=["env line 7: os.environ"],
        changed_line_hints=["jobs/forecast.py:12 in `forecast_for_store`"],
        companion_files=["tests/test_forecast.py"],
    )
    rendered = stable + volatile

    assert "pytest" in rendered
    assert "tests/uta_generated/test_jobs_forecast.py" in rendered
    assert str(context_md) in rendered
    assert "uta query-index --repo . --language python" in rendered
    assert "Do not import target modules during planning" in rendered
    assert "Keep exploration bounded" in rendered
    assert "Ignore any external `[search-mode]`" in rendered
    assert "Do not launch background agents" in rendered
    assert "Do not probe the runtime" in rendered
    assert "Do not use `pytest.importorskip`" in rendered
    assert "Do not write or modify verifier configuration or mutation runtime artifacts" in rendered
    assert "Canonical module: `jobs.forecast`" in rendered
    assert "importlib.util.spec_from_file_location" in rendered
    assert "mutmut must see tests execute the real mutated module" in rendered
    assert "CI CHANGED LINES TO COVER" in rendered
    assert "jobs/forecast.py:12 in `forecast_for_store`" in rendered
    assert "monkeypatch" in rendered
    assert "os.environ" in rendered


def test_python_batch_generator_owns_one_standalone_prompt_scope(monkeypatch, tmp_path):
    repo = tmp_path / "repo"
    repo.mkdir()
    runner_home = tmp_path / "runner"
    monkeypatch.setenv("UTA_RUNNER_HOME", str(runner_home))
    request = BatchGenerationRequest.from_targets(
        language="python",
        repo_path=repo,
        targets=[],
    )
    observed = {}

    class ScopeObservingWorkflow:
        def invoke(self, state):
            scope = state["backend_context"]["prompt_artifact_scope"]
            first = scope.durable_directory(
                unit_id="unit-1",
                operation_id="operation-1",
            )
            second = scope.durable_directory(
                unit_id="unit-2",
                operation_id="operation-2",
            )
            observed.update(
                scope=scope,
                first=first,
                second=second,
                run_ids=(scope.run_id, scope.run_id),
            )
            return {**state, "results": {}, "finished": True}

    result = PythonBatchGenerator(workflow_app=ScopeObservingWorkflow()).run(request)

    scope = observed["scope"]
    assert result.final_state["finished"] is True
    assert scope.managed is True
    assert scope.ephemeral_root is not None
    assert observed["run_ids"][0] == observed["run_ids"][1]
    assert scope.run_id in observed["first"].parts
    assert scope.run_id in observed["second"].parts
    assert not Path(scope.ephemeral_root).exists()


def test_python_existing_test_discovery_rejects_broad_content_only_tests(tmp_path):
    repo = tmp_path / "repo"
    source = repo / "chat_robot" / "service" / "fine_tuning_service.py"
    source.parent.mkdir(parents=True)
    source.write_text("def dispatch_fine_tuning_run(run):\n    return run\n", encoding="utf-8")
    pure = repo / "tests" / "test_fine_tuning_pure.py"
    pure.parent.mkdir(parents=True)
    pure.write_text(
        "MODULE = 'chat_robot/service/fine_tuning_service.py'\n"
        "def test_fine_tuning_service_helpers_work_without_django_runtime():\n"
        "    assert MODULE\n",
        encoding="utf-8",
    )
    control = repo / "chat_robot" / "test" / "test_fine_tuning_control_plane.py"
    control.parent.mkdir(parents=True)
    control.write_text(
        "from chat_robot.service import fine_tuning_service\n"
        "def test_control_plane():\n"
        "    assert fine_tuning_service\n",
        encoding="utf-8",
    )
    target = default_registry().adapter_for("python").normalize_target(
        RawTargetSelection(target="chat_robot/service/fine_tuning_service.py")
    )

    matches = discover_strict_python_test_candidates(
        repo,
        target,
        context_payload={"symbols": [{"name": "dispatch_fine_tuning_run"}]},
    )

    assert matches == []
    assert select_python_test_destination(repo, target, context_payload={}).path == (
        "tests/uta_generated/test_chat_robot_service_fine_tuning_service.py"
    )


def test_python_existing_test_discovery_accepts_strict_target_named_test(tmp_path):
    repo = tmp_path / "repo"
    source = repo / "chat_robot" / "service" / "prompt_optimization" / "orchestrator.py"
    source.parent.mkdir(parents=True)
    source.write_text("def orchestrate():\n    return True\n", encoding="utf-8")
    broad = repo / "tests" / "test_fine_tuning_pure.py"
    broad.parent.mkdir(parents=True)
    broad.write_text("from chat_robot.service.prompt_optimization import orchestrator\n", encoding="utf-8")
    check = repo / "chat_robot" / "test" / "check_test.py"
    check.parent.mkdir(parents=True)
    check.write_text("from chat_robot.service.prompt_optimization import orchestrator\n", encoding="utf-8")
    strict = repo / "tests" / "test_prompt_optimization_orchestrator.py"
    strict.write_text("from chat_robot.service.prompt_optimization import orchestrator\n", encoding="utf-8")
    target = default_registry().adapter_for("python").normalize_target(
        RawTargetSelection(target="chat_robot/service/prompt_optimization/orchestrator.py")
    )

    matches = discover_strict_python_test_candidates(repo, target, context_payload={})

    assert [match.path for match in matches] == ["tests/test_prompt_optimization_orchestrator.py"]
    assert select_python_test_destination(repo, target, context_payload={}).path == (
        "tests/test_prompt_optimization_orchestrator.py"
    )


def test_python_existing_test_discovery_rejects_generic_context_symbol_match(tmp_path):
    repo = tmp_path / "repo"
    source = repo / "chat_robot" / "service" / "prompt_optimization" / "orchestrator.py"
    source.parent.mkdir(parents=True)
    source.write_text(
        "class PromptOptimizationOrchestrator:\n"
        "    def check(self):\n"
        "        return True\n",
        encoding="utf-8",
    )
    check = repo / "chat_robot" / "test" / "check_test.py"
    check.parent.mkdir(parents=True)
    check.write_text(
        "from chat_robot.service.prompt_optimization.orchestrator import PromptOptimizationOrchestrator\n\n"
        "def test_check():\n"
        "    assert PromptOptimizationOrchestrator().check()\n",
        encoding="utf-8",
    )
    target = default_registry().adapter_for("python").normalize_target(
        RawTargetSelection(target="chat_robot/service/prompt_optimization/orchestrator.py")
    )
    context_payload = {
        "symbols": [
            {"name": "check"},
            {"name": "PromptOptimizationOrchestrator"},
        ]
    }

    matches = discover_strict_python_test_candidates(repo, target, context_payload=context_payload)

    assert matches == []
    assert select_python_test_destination(repo, target, context_payload=context_payload).path == (
        "tests/uta_generated/test_chat_robot_service_prompt_optimization_orchestrator.py"
    )


def test_python_existing_test_discovery_uses_deterministic_tie_breaks(tmp_path):
    repo = tmp_path / "repo"
    source = repo / "jobs" / "forecast.py"
    source.parent.mkdir(parents=True)
    source.write_text("def forecast():\n    return 1\n", encoding="utf-8")
    tests_dir = repo / "tests"
    (tests_dir / "unit").mkdir(parents=True)
    (tests_dir / "z").mkdir(parents=True)
    (tests_dir / "test_forecast.py").write_text("def test_forecast():\n    assert True\n", encoding="utf-8")
    (tests_dir / "unit" / "test_forecast.py").write_text("def test_forecast_unit():\n    assert True\n", encoding="utf-8")
    (tests_dir / "z" / "test_forecast.py").write_text("def test_forecast_z():\n    assert True\n", encoding="utf-8")
    target = default_registry().adapter_for("python").normalize_target(RawTargetSelection(target="jobs/forecast.py"))

    matches = discover_strict_python_test_candidates(repo, target, context_payload={})

    assert [match.path for match in matches[:3]] == [
        "tests/test_forecast.py",
        "tests/z/test_forecast.py",
        "tests/unit/test_forecast.py",
    ]
