"""Deterministic partitioning of mutation work into byte-budgeted batches.

Implements the core of ADR-002 / design-python-mutation-batched-generation.md: split the
selected mutation opportunities of one source file into function-granular batches, each
under a generated-bytes budget, so each generated mutmut module stays in CPython's linear
parse regime (see design-python-mutation-scalability.md Appendix A 13.7).

A "unit" is the code mutmut copies once per mutant: a top-level function or a class method
(module-level code is not mutated by mutmut 3). Whole-function partitioning keeps every
unit's mutmut keys inside a single batch, avoiding the per-generation ``__mutmut_N`` key
collision described in Appendix A 13.9.

This module is intentionally pure (no I/O, no mutmut import) so the partition logic is
unit-testable in isolation; the runner builds ``MutationUnit``s from the source tree.
"""

from __future__ import annotations

import ast
import hashlib
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Mapping, Sequence, Tuple

# Matches mutmut's class/method name separator
# (mutmut.trampoline_templates.CLASS_NAME_SEPARATOR) and the symbol naming in
# this package's own `mutation_candidates`, so unit symbols line up with the
# mutmut mangled key prefixes used when mapping generated keys back to
# opportunities.
CLASS_NAME_SEPARATOR = "ǁ"


@dataclass(frozen=True)
class MutationUnit:
    """A top-level function / class method that mutmut copies once per mutant.

    ``unit_bytes`` is the source size of the copied unit; ``lines`` are the selected
    (one-operator-per-line) mutation lines inside it; ``priority`` orders retention when
    trimming is forced (higher = kept first).
    """

    symbol: str
    unit_bytes: int
    lines: Tuple[int, ...]
    priority: int = 0


@dataclass(frozen=True)
class BatchPlan:
    index: int
    symbols: Tuple[str, ...]
    lines: Tuple[int, ...]
    estimated_bytes: int


@dataclass(frozen=True)
class PartitionResult:
    batches: Tuple[BatchPlan, ...]
    signature: str
    omitted_by_generated_bytes_cap: Tuple[int, ...]
    omitted_by_max_batches: Tuple[int, ...]


def estimated_generated_bytes(unit_bytes: int, n_lines: int) -> int:
    """Generated bytes for ``n_lines`` mutants of a unit: one ``_orig`` copy + one copy per
    mutant (each a full copy of the unit). Trampoline overhead is left to budget headroom."""
    return (n_lines + 1) * max(0, int(unit_bytes))


class _Bin:
    __slots__ = ("used", "symbols", "lines")

    def __init__(self) -> None:
        self.used = 0
        self.symbols: List[str] = []
        self.lines: List[int] = []


def partition_units_into_batches(
    units: Sequence[MutationUnit],
    *,
    budget: int,
    max_batches: int,
) -> PartitionResult:
    """Bin-pack whole units into <= ``max_batches`` batches, each <= ``budget`` bytes.

    - A unit larger than the budget is capped to the lines that fit (keeping the lowest
      line numbers deterministically); dropped lines are reported in
      ``omitted_by_generated_bytes_cap``. A single unit that cannot fit even one mutant
      under budget gets its own over-budget batch (one line kept).
    - When the budget would need more than ``max_batches`` batches, the lowest-priority
      units that do not fit are dropped into ``omitted_by_max_batches``.

    Deterministic: processing order is (priority desc, symbol asc); final batches are
    ordered by their smallest line so the index and signature are stable for fixed input.
    """
    budget = int(budget)
    max_batches = max(1, int(max_batches))

    ordered = sorted(units, key=lambda u: (-int(u.priority), str(u.symbol)))

    bins: List[_Bin] = []
    cap_omitted: List[int] = []
    max_omitted: List[int] = []

    for unit in ordered:
        lines = sorted(int(x) for x in unit.lines)
        if not lines:
            continue

        # Oversized cap: keep as many lines as fit under budget (at least one).
        if unit.unit_bytes > 0 and budget > 0:
            max_lines_fit = budget // unit.unit_bytes - 1
            if max_lines_fit < len(lines):
                keep_n = max(1, max_lines_fit)
                cap_omitted.extend(lines[keep_n:])
                lines = lines[:keep_n]
        est = estimated_generated_bytes(unit.unit_bytes, len(lines))

        placed = False
        if est <= budget:
            for b in bins:
                if b.used + est <= budget:
                    b.used += est
                    b.symbols.append(unit.symbol)
                    b.lines.extend(lines)
                    placed = True
                    break
        if not placed:
            if len(bins) < max_batches:
                b = _Bin()
                b.used = est
                b.symbols = [unit.symbol]
                b.lines = list(lines)
                bins.append(b)
            else:
                # No room in any existing batch and the batch budget (count) is exhausted.
                max_omitted.extend(lines)

    ordered_bins = sorted((b for b in bins if b.lines), key=lambda b: min(b.lines))
    batches = tuple(
        BatchPlan(
            index=i,
            symbols=tuple(b.symbols),
            lines=tuple(sorted(b.lines)),
            estimated_bytes=b.used,
        )
        for i, b in enumerate(ordered_bins)
    )

    signature = _signature(batches)
    return PartitionResult(
        batches=batches,
        signature=signature,
        omitted_by_generated_bytes_cap=tuple(sorted(cap_omitted)),
        omitted_by_max_batches=tuple(sorted(max_omitted)),
    )


def _signature(batches: Sequence[BatchPlan]) -> str:
    payload = "|".join(",".join(str(ln) for ln in b.lines) for b in batches)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


_CONCAT_LIST_FIELDS = (
    "eligibleMutationOpportunities",
    "suppressed",
    "reportFullSelected",
    "activeSelected",
    "omittedByOnePerLine",
    "opportunityIds",
    "reportFullCandidateIds",
    "activeCandidateIds",
    "activeToolCandidateKeys",
    "exactToolCandidateKeys",
)
_UNION_SORTED_FIELDS = (
    "changedLines",
    "executableChangedLines",
    "coveredChangedLines",
    "selectedTestPaths",
)
_SUM_COUNT_FIELDS = (
    "eligibleMutationCandidates",
    "reportFullSelectedCandidates",
    "selectedCandidates",
    "suppressedCandidates",
    "exactToolCandidateKeyCount",
    "runMutants",
    "scoredMutants",
    "killed",
    "survived",
    "noTests",
    "timeout",
    "suspicious",
)
# Scalar metadata identical across batches (same source/config); taken from the first plan.
_SCALAR_CARRY_FIELDS = (
    "language",
    "targetId",
    "sourcePath",
    "policyMode",
    "filterMechanism",
    "plannerVersion",
    "aridRuleVersion",
    "testSelectionPolicyVersion",
    "suppressionPolicyVersion",
    "operatorPolicyVersion",
    "mutationToolApiFingerprint",
    "mutationToolConfigFingerprint",
    "runtimeFingerprint",
    "dependencyFingerprint",
    "repoUrl",
    "baseRef",
    "baseCommit",
    "headCommit",
    "selectedKeyExecutionApplied",
    "adapterFilteredGenerationApplied",
)


def aggregate_batch_candidate_plans(
    plans: Sequence[dict],
    *,
    partition_signature: str,
    max_generated_bytes: int,
    batches_meta: Sequence[dict],
    omitted_by_generated_bytes_cap: Sequence[int],
    omitted_by_max_batches: Sequence[int],
) -> dict:
    """Merge per-batch candidate-plan dicts into one aggregate plan (T5 / ADR-002).

    Counts are summed and list fields concatenated (each batch's functions are disjoint, so
    opportunity ids and tool keys stay distinct — no cross-batch key collision). The
    aggregate ``candidatePlanId`` is recomputed from the child plan ids plus the partition
    signature, batch count, and byte budget so reruns with identical inputs stay comparable.
    Returns ``{}`` for an empty batch list.
    """
    plans = [p for p in plans if isinstance(p, dict) and p]
    if not plans:
        return {}

    agg: dict = {}
    base = plans[0]
    for field_name in _SCALAR_CARRY_FIELDS:
        if field_name in base:
            agg[field_name] = base[field_name]

    for field_name in _CONCAT_LIST_FIELDS:
        merged: List = []
        for p in plans:
            value = p.get(field_name)
            if isinstance(value, (list, tuple)):
                merged.extend(value)
        agg[field_name] = merged

    for field_name in _UNION_SORTED_FIELDS:
        union: set = set()
        for p in plans:
            value = p.get(field_name)
            if isinstance(value, (list, tuple)):
                union.update(value)
        if union:
            try:
                agg[field_name] = sorted(union)
            except TypeError:
                agg[field_name] = list(union)

    for field_name in _SUM_COUNT_FIELDS:
        total = 0
        for p in plans:
            value = p.get(field_name)
            if isinstance(value, (int, float)):
                total += int(value)
        agg[field_name] = total

    # Keep the evidence contract stable even when every child plan has an empty
    # selected/generated set, for example a batch whose adapter generated no mutants.
    for field_name in _CONCAT_LIST_FIELDS:
        agg.setdefault(field_name, [])
    for field_name in _SUM_COUNT_FIELDS:
        agg.setdefault(field_name, 0)

    suppression: Dict[str, int] = {}
    for p in plans:
        by_reason = p.get("suppressionByReason")
        if isinstance(by_reason, dict):
            for reason, count in by_reason.items():
                if isinstance(count, (int, float)):
                    suppression[str(reason)] = suppression.get(str(reason), 0) + int(count)
    agg["suppressionByReason"] = suppression

    agg["generationStrategy"] = "batch"
    agg["batchCount"] = len(plans)
    agg["partitionSignature"] = str(partition_signature)
    agg["maxGeneratedBytes"] = int(max_generated_bytes)
    agg["batches"] = list(batches_meta)
    agg["omittedByGeneratedBytesCap"] = sorted(int(x) for x in omitted_by_generated_bytes_cap)
    agg["omittedByMaxBatches"] = sorted(int(x) for x in omitted_by_max_batches)

    child_ids = sorted(str(p.get("candidatePlanId") or "") for p in plans)
    agg["candidatePlanId"] = _aggregate_plan_id(
        child_ids, str(partition_signature), len(plans), int(max_generated_bytes)
    )
    return agg


def _aggregate_plan_id(child_ids: Sequence[str], signature: str, batch_count: int, budget: int) -> str:
    payload = "|".join(
        [
            "batch",
            str(batch_count),
            str(budget),
            signature,
            ";".join(child_ids),
        ]
    )
    return "batched-" + hashlib.sha256(payload.encode("utf-8")).hexdigest()[:24]


def mutation_units_from_source(
    source: str,
    selected: Iterable[Tuple[int, int]],
) -> List[MutationUnit]:
    """Group selected ``(line, priority)`` pairs into the units mutmut copies per mutant.

    The copy unit mirrors mutmut 3's ``combine_mutations_to_source``: each top-level
    function/async function, and each method of a top-level class (``Class<sep>method``).
    Module-level code is not mutated by mutmut 3, so lines outside any such unit are
    dropped (they would generate no mutant). ``unit_bytes`` is the UTF-8 size of the unit's
    source span; the unit's priority is the max priority of its selected lines.
    """
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []

    # UTF-8 byte length of each source line, computed once (1-indexed via line_bytes[line]).
    line_bytes = [0] + [len(line.encode("utf-8")) for line in source.splitlines(keepends=True)]

    def _unit_bytes(start: int, end: int) -> int:
        return sum(line_bytes[i] for i in range(start, end + 1) if 1 <= i < len(line_bytes))

    # Map every line in a copy unit's span to (symbol, unit_bytes), in one pass. mutmut 3's
    # copy units (top-level functions + top-level class methods) have pairwise-disjoint spans,
    # so a flat line index is unambiguous.
    unit_by_line: Dict[int, Tuple[str, int]] = {}

    def _record(node: ast.AST, symbol: str) -> None:
        start = int(getattr(node, "lineno", 0) or 0)
        end = int(getattr(node, "end_lineno", start) or start)
        if start <= 0:
            return
        nbytes = _unit_bytes(start, end)
        for line in range(start, end + 1):
            unit_by_line[line] = (symbol, nbytes)

    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _record(node, str(node.name))
        elif isinstance(node, ast.ClassDef):
            for method in node.body:
                if isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    _record(method, f"{node.name}{CLASS_NAME_SEPARATOR}{method.name}")

    lines_by_symbol: Dict[str, set] = {}
    bytes_by_symbol: Dict[str, int] = {}
    priority_by_symbol: Dict[str, int] = {}
    for raw_line, priority in selected:
        line = int(raw_line)
        unit = unit_by_line.get(line)
        if unit is None:
            continue
        symbol, nbytes = unit
        lines_by_symbol.setdefault(symbol, set()).add(line)
        bytes_by_symbol[symbol] = nbytes
        priority_by_symbol[symbol] = max(priority_by_symbol.get(symbol, 0), int(priority))

    return [
        MutationUnit(
            symbol=symbol,
            unit_bytes=bytes_by_symbol[symbol],
            lines=tuple(sorted(lines_by_symbol[symbol])),
            priority=priority_by_symbol[symbol],
        )
        for symbol in sorted(lines_by_symbol)
    ]


# -- generation-policy slicing ------------------------------------------------
#
# Partitioning decides *which* lines belong to a batch; these two turn that
# decision into the inputs one batch is generated from. Both are pure, and both
# lanes need them, so they sit beside the partitioner rather than in either
# lane's runner.

#: Policy fields holding per-line opportunity payloads. Each is filtered to the
#: batch's lines; every other field is a scalar and carries through unchanged.
POLICY_LINE_LIST_FIELDS = (
    "selected",
    "selectedLineRepresentatives",
    "selectedBeforeCap",
    "hardCapSelected",
    "omittedByCapOpportunities",
    "omittedByRepresentativeOpportunities",
    "omittedByHardCapOpportunities",
    "omittedByOnePerLineOpportunities",
    "suppressed",
)


def policy_payload_line(item: Any) -> int:
    """The line a policy payload refers to, directly or through its opportunity."""
    if isinstance(item, Mapping):
        if "line" in item:
            try:
                return int(item.get("line"))
            except (TypeError, ValueError):
                return -1
        opportunity = item.get("opportunity")
        if isinstance(opportunity, Mapping) and "line" in opportunity:
            try:
                return int(opportunity.get("line"))
            except (TypeError, ValueError):
                return -1
    return -1


def filter_generation_policy_to_lines(
    policy: Mapping[str, Any], lines: Iterable[int]
) -> Dict[str, Any]:
    """Return the generation policy restricted to one batch's lines.

    Per-batch metadata generation and candidate planning must see only the work
    that batch owns; anything wider and each batch regenerates the whole file,
    which is the scaling problem batching exists to solve.
    """
    line_set = {int(line) for line in lines}
    filtered: Dict[str, Any] = dict(policy)
    for field_name in POLICY_LINE_LIST_FIELDS:
        value = policy.get(field_name)
        if isinstance(value, list):
            filtered[field_name] = [
                item for item in value if policy_payload_line(item) in line_set
            ]
    for field_name in ("selectedLines", "allowedLines"):
        value = policy.get(field_name)
        if isinstance(value, list):
            filtered[field_name] = sorted(int(x) for x in value if int(x) in line_set)
    for field_name in ("operatorByLine", "opportunityIdByLine"):
        value = policy.get(field_name)
        if isinstance(value, dict):
            filtered[field_name] = {
                key: item for key, item in value.items() if int(key) in line_set
            }
    return filtered


def mutation_units_from_generation_policy(
    source_text: str, selected: Sequence[Any]
) -> List[MutationUnit]:
    """Build partition units from a policy's selections, carrying ROI priority.

    Higher ``operatorPriority`` is a more valuable opportunity, and the
    partitioner keeps higher-priority units first when the max-batch guard
    forces a trim -- so dropping the field here would silently randomize which
    mutations survive that trim.
    """
    pairs = [
        (int(item["line"]), int(item.get("operatorPriority", 0) or 0))
        for item in selected
        if isinstance(item, Mapping) and "line" in item
    ]
    return mutation_units_from_source(source_text, pairs)
