from __future__ import annotations

from dataclasses import dataclass
import re
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional

from uta.engine.batch import BatchGenerationRequest, BatchGenerationResult
from uta.config import settings
from uta.engine.learning import TargetLearningKey
from uta.engine.scoring import default_scorer_registry
from uta.engine.verification import VerificationRunnerRegistry
from uta.language.python.verification import PythonVerificationRunner
from uta.learning import load_prior_hints, record_run_inefficiencies
from uta.opencode.fallback import poll_completion_with_task_guard
from uta.prompts.loader import render_prompt_split
from uta.tasks.models import TERMINAL_CLASS_STATUSES, json_loads
from uta.engine.validation import (
    BreadthVerdict,
    FeasibilityVerdict,
    validate_plan_breadth,
    validate_plan_feasibility,
)
from uta.language.python.verification.runner import PythonVerificationResult, verify_python_target
from uta.language.python.context_builder import PythonContextBuilder
from uta.engine.targets import TargetRef


GENERATED_ROOT = Path("tests") / "uta_generated"
OWNERSHIP_MARKER = "Generated by UTA. Safe to update."


@dataclass(frozen=True)
class PythonBatchGenerationResult(BatchGenerationResult):
    pass


class PythonBatchGenerator:
    language = "python"

    def __init__(
        self,
        *,
        client_factory: Optional[Callable[[str], Any]] = None,
        verification_runner: Optional[Callable[..., PythonVerificationResult]] = None,
    ):
        self.client_factory = client_factory
        self.verification_runner = verification_runner

    def run(self, request: BatchGenerationRequest) -> PythonBatchGenerationResult:
        if request.language != "python":
            raise ValueError(f"PythonBatchGenerator cannot run language={request.language!r}")
        return run_python_batch_request(
            request,
            client_factory=self.client_factory,
            verification_runner=self.verification_runner,
        )


def generated_test_path(target: TargetRef) -> str:
    source_path = target.source_path or _source_path_from_target(target.target_id)
    source_stem = source_path[:-3] if source_path.endswith(".py") else source_path
    slug = re.sub(r"[^A-Za-z0-9]+", "_", source_stem).strip("_").lower()
    return (GENERATED_ROOT / f"test_{slug or 'python_target'}.py").as_posix()


def render_generated_test_file(target: TargetRef, *, body: str = "") -> str:
    content = body.rstrip()
    if content:
        content = f"\n\n{content}\n"
    else:
        content = "\n\n"
    return (
        f"# {OWNERSHIP_MARKER}\n"
        f"# UTA_TARGET_ID: {target.target_id}\n"
        f"# UTA_SOURCE_PATH: {target.source_path or _source_path_from_target(target.target_id)}\n"
        f"# UTA_SYMBOL: {target.symbol or ''}\n"
        f"# UTA_GRANULARITY: {target.granularity}\n"
        f"{content}"
    )


def write_generated_test_file(repo_path: Path, target: TargetRef, content: str) -> Path:
    repo = Path(repo_path)
    relative = Path(generated_test_path(target))
    destination = repo / relative
    if destination.exists() and not is_uta_owned_test(destination.read_text(encoding="utf-8", errors="replace")):
        raise ValueError(f"Refusing to overwrite file that is not UTA-owned: {relative.as_posix()}")
    if not is_uta_owned_test(content):
        content = render_generated_test_file(target, body=content)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return destination


def run_python_batch_generation(
    *,
    repo_path: Path,
    targets: Iterable[TargetRef],
    task_id: Optional[int] = None,
    task_db_path: Optional[Path] = None,
    client_factory: Optional[Callable[[str], Any]] = None,
    verification_runner: Optional[Callable[..., PythonVerificationResult]] = None,
    model_id: Optional[str] = None,
    coverage_gate: Optional[float] = None,
    mutation_gate: Optional[float] = None,
    timeout_seconds: int = 1800,
) -> PythonBatchGenerationResult:
    return run_python_batch_request(
        BatchGenerationRequest(
            language="python",
            repo_path=Path(repo_path),
            targets=list(targets or []),
            task_id=task_id,
            task_db_path=Path(task_db_path) if task_db_path else None,
            model_id=model_id,
            coverage_gate=coverage_gate,
            mutation_gate=mutation_gate,
            timeout_seconds=timeout_seconds,
        ),
        client_factory=client_factory,
        verification_runner=verification_runner,
    )


def run_python_batch_request(
    request: BatchGenerationRequest,
    *,
    client_factory: Optional[Callable[[str], Any]] = None,
    verification_runner: Optional[Callable[..., PythonVerificationResult]] = None,
) -> PythonBatchGenerationResult:
    if request.language != "python":
        raise ValueError(f"Python batch generation requires language='python', got {request.language!r}")
    repo = Path(request.repo_path).expanduser().resolve()
    target_refs = list(request.targets or [])
    client = _make_client(str(repo), client_factory=client_factory)
    context_builder = PythonContextBuilder(repo)
    results: Dict[str, Dict[str, Any]] = {}
    session_ids: List[str] = []
    session_token_usage = _empty_session_token_usage()
    retrospect_hints: List[str] = []
    scorer = default_scorer_registry().scorer_for("python")

    manager = None
    if request.task_id and request.task_db_path:
        from uta.tasks.manager import TaskManager

        manager = TaskManager(request.task_db_path)
        target_refs = _skip_terminal_task_targets(manager, int(request.task_id), target_refs)
        manager.record_stage_for_targets(int(request.task_id), "python_context", targets=target_refs)
    changed_lines = _changed_lines_from_task_context(manager, int(request.task_id)) if manager and request.task_id else None

    for target in target_refs:
        learning_key = _target_learning_key(target)
        context_payload = context_builder.build_target_context(target)
        context_paths = context_builder.export_target_context(target)
        score_result = scorer.score_target(repo, target, context_payload=context_payload)
        prior_hints = load_prior_hints(repo.as_posix(), target_key=learning_key)["prompt_lines"]
        generated_rel = generated_test_path(target)
        generated_abs = repo / generated_rel
        generated_preexisted = generated_abs.exists()
        generated_before = generated_abs.read_text(encoding="utf-8", errors="replace") if generated_preexisted else None
        if manager and request.task_id and generated_preexisted and generated_before and is_uta_owned_test(generated_before):
            manager.record_stage_for_targets(int(request.task_id), "python_verify", targets=[target])
            existing_verification = _verify_generated_test(
                repo,
                target,
                generated_abs,
                context_payload=context_payload,
                verification_runner=verification_runner,
                coverage_gate=float(request.coverage_gate if request.coverage_gate is not None else settings.coverage_gate),
                mutation_gate=float(request.mutation_gate if request.mutation_gate is not None else settings.mutation_gate),
                changed_lines=changed_lines,
            )
            if existing_verification.status == "passed":
                results[target.target_id] = _target_result_payload(
                    target,
                    verification=existing_verification,
                    generated_abs=generated_abs,
                    repo=repo,
                    session_ids=[],
                    phase_usage={},
                    score_result=score_result.as_dict(),
                    validation={"existing_test_preverified": True, "passed": True},
                )
                manager.sync_target_results(
                    int(request.task_id),
                    {target.target_id: results[target.target_id]},
                    targets=[target],
                    final_error=None,
                )
                continue
        if manager:
            manager.record_stage_for_targets(int(request.task_id), "python_generate", targets=[target])
        stable_prompt, volatile_prompt = render_prompt_split(
            "python_generate_test",
            target_id=target.target_id,
            display_name=target.display_name,
            source_path=target.source_path or _source_path_from_target(target.target_id),
            symbol=target.symbol or "",
            generated_test_path=generated_rel,
            context_abs=context_paths["context_abs"],
            context_json_abs=context_paths["json_abs"],
            index_query_command=(
                "uta query-index --repo . --language python "
                f"--target {target.display_name} --json-output"
            ),
            syntax_version=(context_payload.get("syntax") or {}).get("version") or "unknown",
            parser_backend=(context_payload.get("syntax") or {}).get("parser_backend") or "tree_sitter",
            side_effect_hints=_format_side_effect_hints(context_payload.get("side_effect_hints") or []),
            changed_line_hints=_format_changed_line_hints(target, changed_lines, context_payload),
            companion_files=[
                item.get("path")
                for item in context_payload.get("companion_files") or []
                if item.get("path")
            ],
            scored_methods=_prompt_scored_methods(score_result.methods),
            prior_hints=prior_hints,
        )
        session_id = client.create_session(model_id=request.model_id)
        session_ids.append(session_id)
        client.send_message_split(session_id, stable_prompt, volatile_prompt, model_id=request.model_id)
        event = _poll_completion_with_task_guard(
            client,
            session_id,
            timeout_seconds=request.timeout_seconds,
            guard_state=_task_guard_state(repo, task_id=request.task_id, task_db_path=request.task_db_path),
            batch=[target.target_id],
            phase="python_generate",
        )
        response_text = str(event.get("result") or "")
        if event.get("type") not in {"completed", "message"}:
            message = _event_error_message(event)
            body = _generated_body_from_response_or_new_file(
                "",
                generated_abs=generated_abs,
                generated_preexisted=generated_preexisted,
                generated_before=generated_before,
            )
            if not _looks_like_python_test(body):
                results[target.target_id] = {
                    "status": "PROVIDER_ERROR",
                    "language": target.language,
                    "target_id": target.target_id,
                    "display_name": target.display_name,
                    "source_path": target.source_path,
                    "target_granularity": target.granularity,
                    "coverage": 0.0,
                    "tests_pass": False,
                    "mutation_score": 0.0,
                    "error": message,
                    "session_ids": [session_id],
                }
                if manager:
                    manager.sync_target_results(
                        int(request.task_id),
                        {target.target_id: results[target.target_id]},
                        targets=[target],
                        final_error=None,
                    )
                continue
            validation = _validate_python_generation_response(
                body,
                context_payload=context_payload,
                scored_methods=score_result.methods,
                coverage_gate=float(request.coverage_gate if request.coverage_gate is not None else settings.coverage_gate),
            )
            validation["provider_recovered"] = message
        else:
            validation = _validate_python_generation_response(
                response_text,
                context_payload=context_payload,
                scored_methods=score_result.methods,
                coverage_gate=float(request.coverage_gate if request.coverage_gate is not None else settings.coverage_gate),
            )
            body = _generated_body_from_response_or_new_file(
                response_text,
                generated_abs=generated_abs,
                generated_preexisted=generated_preexisted,
                generated_before=generated_before,
            )
        if not _looks_like_python_test(body):
            if generated_preexisted and generated_before is not None:
                generated_abs.write_text(generated_before, encoding="utf-8")
            results[target.target_id] = {
                "status": "PROVIDER_ERROR",
                "language": target.language,
                "target_id": target.target_id,
                "display_name": target.display_name,
                "source_path": target.source_path,
                "symbol": target.symbol,
                "target_granularity": target.granularity,
                "coverage": 0.0,
                "tests_pass": False,
                "mutation_score": 0.0,
                "error": "OpenCode did not produce a Python pytest test file",
                "session_ids": [session_id],
            }
            if manager:
                manager.sync_target_results(
                    int(request.task_id),
                    {target.target_id: results[target.target_id]},
                    targets=[target],
                    final_error=None,
                )
            continue
        generated_abs = write_generated_test_file(repo, target, body)
        if manager:
            manager.record_stage_for_targets(int(request.task_id), "python_verify", targets=[target])
        verification = _verify_generated_test(
            repo,
            target,
            generated_abs,
            context_payload=context_payload,
            verification_runner=verification_runner,
            coverage_gate=float(request.coverage_gate if request.coverage_gate is not None else settings.coverage_gate),
            mutation_gate=float(request.mutation_gate if request.mutation_gate is not None else settings.mutation_gate),
            changed_lines=changed_lines,
        )
        repair_session_ids, repair_phase_usage, verification = _run_python_repair_loop(
            client,
            repo=repo,
            target=target,
            generated_abs=generated_abs,
            verification=verification,
            context_payload=context_payload,
            context_paths=context_paths,
            request=request,
            manager=manager,
            verification_runner=verification_runner,
            changed_lines=changed_lines,
        )
        session_ids.extend(repair_session_ids)
        for repair_session_id in repair_session_ids:
            _merge_session_token_usage(session_token_usage, _safe_analyze_tokens(client, repair_session_id))
        token_usage = _safe_analyze_tokens(client, session_id)
        _merge_session_token_usage(session_token_usage, token_usage)
        retrospect = _safe_analyze_retrospect(client, session_id)
        retrospect_hints.extend(str(item) for item in retrospect.get("hints") or [] if item)
        phase_usage = {"generate": dict((token_usage.get("total_tokens") or {}))}
        phase_usage.update(repair_phase_usage)
        results[target.target_id] = _target_result_payload(
            target,
            verification=verification,
            generated_abs=generated_abs,
            repo=repo,
            session_ids=[session_id, *repair_session_ids],
            phase_usage=phase_usage,
            score_result=score_result.as_dict(),
            validation=validation,
        )
        record_run_inefficiencies(
            repo.as_posix(),
            target_key=learning_key,
            phase_tokens=phase_usage,
            repeated_tools=list(retrospect.get("repeated_tools") or []),
        )
        if manager:
            manager.sync_target_results(
                int(request.task_id),
                {target.target_id: results[target.target_id]},
                targets=[target],
                final_error=None,
            )

    session_retrospect = {
        "target_ids": [target.target_id for target in target_refs],
        "hints": list(dict.fromkeys(retrospect_hints)),
    }
    if manager:
        manager.sync_target_results(
            int(request.task_id),
            {},
            targets=target_refs,
            session_token_usage=session_token_usage,
            final_error=None,
        )
    return PythonBatchGenerationResult(
        results=results,
        session_ids=session_ids,
        session_token_usage=session_token_usage,
        session_retrospect=session_retrospect,
    )


def _target_result_payload(
    target: TargetRef,
    *,
    verification: PythonVerificationResult,
    generated_abs: Path,
    repo: Path,
    session_ids: List[str],
    phase_usage: Dict[str, Any],
    score_result: Dict[str, Any],
    validation: Dict[str, Any],
) -> Dict[str, Any]:
    return {
        **verification.as_result_fields(),
        "language": target.language,
        "target_id": target.target_id,
        "display_name": target.display_name,
        "source_path": target.source_path,
        "symbol": target.symbol,
        "target_granularity": target.granularity,
        "test_file_path": generated_abs.relative_to(repo).as_posix(),
        "test_file_content": generated_abs.read_text(encoding="utf-8", errors="replace"),
        "session_ids": session_ids,
        "phase_token_usage": phase_usage,
        "target_score": score_result,
        "plan_validation": validation,
    }


def _run_python_repair_loop(
    client: Any,
    *,
    repo: Path,
    target: TargetRef,
    generated_abs: Path,
    verification: PythonVerificationResult,
    context_payload: Dict[str, Any],
    context_paths: Dict[str, str],
    request: BatchGenerationRequest,
    manager: Any,
    verification_runner: Optional[Callable[..., PythonVerificationResult]],
    changed_lines: Optional[Dict[str, List[int]]] = None,
) -> tuple[List[str], Dict[str, Any], PythonVerificationResult]:
    repair_session_ids: List[str] = []
    phase_usage: Dict[str, Any] = {}
    max_attempts = max(0, int(settings.python_repair_max_attempts or 0))
    coverage_gate = float(request.coverage_gate if request.coverage_gate is not None else settings.coverage_gate)
    mutation_gate = float(request.mutation_gate if request.mutation_gate is not None else settings.mutation_gate)
    for attempt in range(1, max_attempts + 1):
        if verification.status == "passed":
            break
        prompt_name = _python_repair_prompt_name(verification)
        if not prompt_name:
            break
        phase = prompt_name
        if manager and request.task_id:
            manager.record_stage_for_targets(int(request.task_id), phase, targets=[target])
        generated_before = generated_abs.read_text(encoding="utf-8", errors="replace") if generated_abs.exists() else None
        stable_prompt, volatile_prompt = render_prompt_split(
            prompt_name,
            target_id=target.target_id,
            display_name=target.display_name,
            source_path=target.source_path or _source_path_from_target(target.target_id),
            symbol=target.symbol or "",
            generated_test_path=generated_abs.relative_to(repo).as_posix(),
            test_file_path=generated_abs.relative_to(repo).as_posix(),
            context_abs=context_paths["context_abs"],
            context_json_abs=context_paths["json_abs"],
            index_query_command=(
                "uta query-index --repo . --language python "
                f"--target {target.display_name} --json-output"
            ),
            compile_errors=_python_verification_diagnostics(verification),
            coverage_diagnostics=_python_verification_diagnostics(verification),
            mutation_diagnostics=_python_verification_diagnostics(verification),
            coverage_gate=coverage_gate,
            mutation_gate=mutation_gate,
        )
        session_id = client.create_session(model_id=request.model_id)
        repair_session_ids.append(session_id)
        client.send_message_split(session_id, stable_prompt, volatile_prompt, model_id=request.model_id)
        event = _poll_completion_with_task_guard(
            client,
            session_id,
            timeout_seconds=int(settings.opencode_repair_timeout_seconds or request.timeout_seconds),
            guard_state=_task_guard_state(repo, task_id=request.task_id, task_db_path=request.task_db_path),
            batch=[target.target_id],
            phase=phase,
        )
        response_text = str(event.get("result") or "")
        body = _generated_body_from_response_or_new_file(
            response_text,
            generated_abs=generated_abs,
            generated_preexisted=generated_abs.exists(),
            generated_before=generated_before,
        )
        if _looks_like_python_test(body):
            generated_abs = write_generated_test_file(repo, target, body)
        if manager and request.task_id:
            manager.record_stage_for_targets(int(request.task_id), "python_verify", targets=[target])
        verification = _verify_generated_test(
            repo,
            target,
            generated_abs,
            context_payload=context_payload,
            verification_runner=verification_runner,
            coverage_gate=coverage_gate,
            mutation_gate=mutation_gate,
            changed_lines=changed_lines,
        )
        phase_usage[f"{phase}_{attempt}"] = dict((_safe_analyze_tokens(client, session_id).get("total_tokens") or {}))
    return repair_session_ids, phase_usage, verification


def _python_repair_prompt_name(verification: PythonVerificationResult) -> Optional[str]:
    reason = verification.reason_code
    if reason == "coverage_gate_failed":
        return "python_fix_coverage"
    if reason == "mutation_gate_failed":
        return "python_fix_mutations"
    if reason in {
        "test_failed",
        "verification_error",
        "missing_python_runtime",
        "missing_python2_runtime",
        "missing_pytest",
        "missing_coverage",
        "missing_mutmut",
        "missing_python2_mutmut",
        "missing_mutmut_patch_dependency",
        "mutation_backend_failed",
    }:
        return "python_fix_compile"
    return None


def _python_verification_diagnostics(verification: PythonVerificationResult) -> str:
    lines = [
        f"reason={verification.reason_code}",
        f"status={verification.status}",
        f"tests_pass={verification.tests_pass}",
    ]
    if verification.message:
        lines.append(f"message={verification.message}")
    if verification.coverage:
        lines.append(f"coverage={verification.coverage.rate:.4f} gate={verification.coverage.gate:.4f}")
        if verification.coverage.changed_lines:
            lines.append(f"changed_lines={verification.coverage.changed_lines}")
    if verification.mutation:
        lines.append(
            "mutation="
            f"{verification.mutation.rate:.4f} gate={verification.mutation.gate:.4f} "
            f"generated={verification.mutation.generated} survived={verification.mutation.survived}"
        )
        if verification.mutation.diff_survivors:
            lines.append(f"diff_survivors={verification.mutation.diff_survivors}")
        elif verification.mutation.survivors:
            lines.append(f"survivors={verification.mutation.survivors[:20]}")
    for command in verification.commands[-6:]:
        lines.append(f"$ {' '.join(command.command)}")
        lines.append(f"exit={command.exit_code}")
        output = (command.stderr or command.stdout or "").strip()
        if output:
            lines.append(output[-4000:])
    return "\n".join(lines)


def _skip_terminal_task_targets(manager: Any, task_id: int, targets: List[TargetRef]) -> List[TargetRef]:
    """Keep resumed Python runs focused on DB rows that still need work."""
    runnable: List[TargetRef] = []
    for target in targets:
        row = manager.find_target_task(task_id, target)
        if row and row.get("status") in TERMINAL_CLASS_STATUSES:
            continue
        runnable.append(target)
    return runnable


def _target_learning_key(target: TargetRef) -> TargetLearningKey:
    return TargetLearningKey(language=target.language, target_id=target.target_id)


def _prompt_scored_methods(methods: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return [
        {
            "name": item.get("name") or "",
            "effort_band": item.get("effort_band") or "",
            "planning_score": item.get("planning_score", 0.0),
            "body_lines": item.get("body_lines", 0),
        }
        for item in list(methods or [])[:8]
    ]


def _validate_python_generation_response(
    response_text: str,
    *,
    context_payload: Dict[str, Any],
    scored_methods: List[Dict[str, Any]],
    coverage_gate: float,
) -> Dict[str, Any]:
    breadth = validate_plan_breadth(response_text, context_payload, min_coverage_ratio=0.2)
    feasibility = validate_plan_feasibility(
        response_text,
        scored_methods,
        coverage_gate=int(coverage_gate),
    )
    return {
        "breadth": {
            "verdict": breadth.verdict.value,
            "known_methods": breadth.known_methods,
            "planned_methods": breadth.planned_methods,
            "coverage_ratio": breadth.coverage_ratio,
            "message": breadth.message,
        },
        "feasibility": {
            "verdict": feasibility.verdict.value,
            "candidate_methods": feasibility.candidate_methods,
            "score_ratio": feasibility.score_ratio,
            "message": feasibility.message,
        },
        "passed": breadth.verdict != BreadthVerdict.UNDER and feasibility.verdict != FeasibilityVerdict.UNDER,
    }


def is_uta_owned_test(content: str) -> bool:
    head = "\n".join(str(content or "").splitlines()[:8])
    return OWNERSHIP_MARKER in head and "UTA_TARGET_ID:" in head


def extract_python_test_body(text: str) -> str:
    match = re.search(r"```(?:python|py)?\s*\n(?P<body>.*?)```", text or "", flags=re.DOTALL | re.IGNORECASE)
    if match:
        return match.group("body").strip() + "\n"
    return (text or "").strip() + "\n"


def _generated_body_from_response_or_new_file(
    response_text: str,
    *,
    generated_abs: Path,
    generated_preexisted: bool,
    generated_before: Optional[str],
) -> str:
    if generated_abs.exists():
        direct_body = generated_abs.read_text(encoding="utf-8", errors="replace")
        changed = not generated_preexisted or direct_body != (generated_before or "")
        if changed and _looks_like_python_test(direct_body):
            if not is_uta_owned_test(direct_body):
                generated_abs.unlink()
            return direct_body
    return extract_python_test_body(response_text)


def _looks_like_python_test(content: str) -> bool:
    text = content or ""
    return bool(re.search(r"^\s*(def|async\s+def)\s+test_", text, flags=re.MULTILINE))


def _source_path_from_target(target_id: str) -> str:
    raw = str(target_id or "")
    if raw.startswith("pyfile:"):
        return raw[len("pyfile:") :]
    if raw.startswith("pysymbol:"):
        raw = raw[len("pysymbol:") :]
    return raw.split("::", 1)[0]


def _make_client(repo_path: str, *, client_factory: Optional[Callable[[str], Any]]) -> Any:
    if client_factory:
        return client_factory(repo_path)
    from uta.opencode.client import OpenCodeClient

    return OpenCodeClient(repo_path=repo_path)


def _verify_generated_test(
    repo: Path,
    target: TargetRef,
    generated_abs: Path,
    *,
    context_payload: Dict[str, Any],
    verification_runner: Optional[Callable[..., PythonVerificationResult]],
    coverage_gate: float,
    mutation_gate: float,
    changed_lines: Optional[Dict[str, List[int]]] = None,
) -> PythonVerificationResult:
    syntax_version = (context_payload.get("syntax") or {}).get("version") or "python3"
    try:
        registry = VerificationRunnerRegistry(
            (PythonVerificationRunner(verification_runner or verify_python_target),)
        )
        runner = registry.runner_for("python")
        return runner.verify(
            repo,
            target,
            test_paths=[generated_abs.relative_to(repo).as_posix()],
            syntax_version=syntax_version,
            coverage_gate=coverage_gate,
            mutation_gate=mutation_gate,
            changed_lines=changed_lines,
        )
    except Exception as exc:
        return PythonVerificationResult(
            status="failed",
            reason_code="verification_error",
            message=str(exc),
        )


def _changed_lines_from_task_context(manager: Any, task_id: int) -> Optional[Dict[str, List[int]]]:
    task = manager.get_task(task_id)
    if not task:
        return None
    context = json_loads(task.get("ci_context_json") or "{}")
    enforcement = context.get("enforcement") if isinstance(context, dict) else None
    evidence = enforcement.get("evidence") if isinstance(enforcement, dict) else None
    changed = evidence.get("changedLines") or evidence.get("changed_lines") if isinstance(evidence, dict) else None
    if not isinstance(changed, dict):
        return None
    normalized: Dict[str, List[int]] = {}
    for path, lines in changed.items():
        if not path:
            continue
        normalized[str(path)] = sorted({int(line) for line in lines or [] if int(line) > 0})
    return normalized or None


def _task_guard_state(repo: Path, *, task_id: Optional[int], task_db_path: Optional[Path]) -> Optional[Dict[str, Any]]:
    if not task_id or not task_db_path:
        return None
    return {
        "repo_path": str(repo),
        "task_id": int(task_id),
        "task_db_path": str(task_db_path),
        "language": "python",
    }


def _poll_completion_with_task_guard(
    client: Any,
    session_id: str,
    *,
    timeout_seconds: int,
    guard_state: Optional[Dict[str, Any]],
    batch: List[str],
    phase: str,
) -> Dict[str, Any]:
    from uta.graph.nodes import _llm_guard_after, _llm_guard_before

    return poll_completion_with_task_guard(
        client,
        session_id,
        timeout_seconds=timeout_seconds,
        phase=phase,
        guard_state=guard_state,
        batch=batch,
        guard_before=_llm_guard_before,
        guard_after=_llm_guard_after,
    )


def _format_side_effect_hints(items: Iterable[Dict[str, Any]]) -> List[str]:
    hints = []
    for item in items:
        kind = item.get("kind") or "side_effect"
        line = item.get("line")
        detail = item.get("detail") or ""
        hints.append(f"{kind} line {line}: {detail}" if line else f"{kind}: {detail}")
    return hints


def _format_changed_line_hints(
    target: TargetRef,
    changed_lines: Optional[Dict[str, List[int]]],
    context_payload: Dict[str, Any],
) -> List[str]:
    if not changed_lines:
        return []
    source_path = target.source_path or _source_path_from_target(target.target_id)
    target_lines = set(changed_lines.get(source_path) or changed_lines.get(source_path.replace("\\", "/")) or [])
    if not target_lines:
        return []
    symbols = context_payload.get("symbols") or []
    hints: List[str] = []
    for line_number in sorted(target_lines):
        symbol_name = _symbol_for_line(symbols, line_number)
        if symbol_name:
            hints.append(f"{source_path}:{line_number} in `{symbol_name}`")
        else:
            hints.append(f"{source_path}:{line_number}")
    return hints


def _symbol_for_line(symbols: Iterable[Dict[str, Any]], line_number: int) -> Optional[str]:
    best_name = None
    best_line = -1
    for symbol in symbols or []:
        start = int(symbol.get("line") or symbol.get("start_line") or 0)
        end = int(symbol.get("end_line") or start or 0)
        if start <= line_number <= end and start >= best_line:
            best_name = str(symbol.get("name") or symbol.get("symbol") or "")
            best_line = start
    return best_name or None


def _event_error_message(event: Dict[str, Any]) -> str:
    error = event.get("error") if isinstance(event, dict) else {}
    data = error.get("data") if isinstance(error, dict) else {}
    return str((data or {}).get("message") or event.get("reason") or "Python generation failed")


def _empty_token_bucket() -> Dict[str, int]:
    return {"input": 0, "output": 0, "reasoning": 0, "cache_read": 0, "cache_write": 0, "total": 0}


def _empty_session_token_usage() -> Dict[str, Any]:
    return {
        "main_model_tokens": _empty_token_bucket(),
        "small_model_tokens": _empty_token_bucket(),
        "other_model_tokens": _empty_token_bucket(),
        "total_tokens": _empty_token_bucket(),
    }


def _merge_bucket(dest: Dict[str, int], src: Dict[str, Any]) -> None:
    for key in ("input", "output", "reasoning", "cache_read", "cache_write", "total"):
        dest[key] = int(dest.get(key, 0) or 0) + int(src.get(key, 0) or 0)


def _merge_session_token_usage(dest: Dict[str, Any], src: Dict[str, Any]) -> None:
    for bucket_name in ("main_model_tokens", "small_model_tokens", "other_model_tokens", "total_tokens"):
        _merge_bucket(dest.setdefault(bucket_name, _empty_token_bucket()), src.get(bucket_name) or {})


def _safe_analyze_tokens(client: Any, session_id: str) -> Dict[str, Any]:
    analyzer = getattr(client, "analyze_session_tokens", None)
    if not callable(analyzer):
        return _empty_session_token_usage()
    try:
        return analyzer(session_id) or _empty_session_token_usage()
    except Exception:
        return _empty_session_token_usage()


def _safe_analyze_retrospect(client: Any, session_id: str) -> Dict[str, Any]:
    analyzer = getattr(client, "analyze_session_retrospect", None)
    if not callable(analyzer):
        return {}
    try:
        return analyzer(session_id) or {}
    except Exception:
        return {}
