"""Deterministic ownership and materialization of generated Python tests."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from uta.language.python.module_resolver import resolve_python_module
from uta.language.python.test_selection import (
    generated_test_path,
    source_path_from_target,
)
from uta.shared.targets import TargetRef


OWNERSHIP_MARKER = "Generated by UTA. Safe to update."


def render_generated_test_file(target: TargetRef, *, body: str = "") -> str:
    content = body.rstrip()
    content = f"\n\n{content}\n" if content else "\n\n"
    return (
        f"# {OWNERSHIP_MARKER}\n"
        f"# UTA_TARGET_ID: {target.target_id}\n"
        f"# UTA_SOURCE_PATH: "
        f"{target.source_path or source_path_from_target_id(target.target_id)}\n"
        f"# UTA_SYMBOL: {target.symbol or ''}\n"
        f"# UTA_GRANULARITY: {target.granularity}\n"
        f"{content}"
    )


def write_generated_test_file(
    repo_path: Path, target: TargetRef, content: str
) -> Path:
    return write_python_test_file(
        repo_path,
        target,
        content,
        relative_path=generated_test_path(target),
        allow_existing_non_uta=False,
    )


def write_python_test_file(
    repo_path: Path,
    target: TargetRef,
    content: str,
    *,
    relative_path: str,
    allow_existing_non_uta: bool,
) -> Path:
    repo = Path(repo_path)
    relative = Path(relative_path)
    destination = repo / relative
    if (
        destination.exists()
        and not allow_existing_non_uta
        and not is_uta_owned_test(
            destination.read_text(encoding="utf-8", errors="replace")
        )
    ):
        raise ValueError(
            f"Refusing to overwrite file that is not UTA-owned: {relative.as_posix()}"
        )
    if not allow_existing_non_uta and not is_uta_owned_test(content):
        content = render_generated_test_file(target, body=content)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(content, encoding="utf-8")
    return destination


def is_uta_owned_test(content: str) -> bool:
    head = "\n".join(str(content or "").splitlines()[:8])
    return OWNERSHIP_MARKER in head and "UTA_TARGET_ID:" in head


def extract_python_test_body(text: str) -> str:
    match = re.search(
        r"```(?:python|py)?\s*\n(?P<body>.*?)```",
        text or "",
        flags=re.DOTALL | re.IGNORECASE,
    )
    if match:
        return match.group("body").strip() + "\n"
    return (text or "").strip() + "\n"


def generated_body_from_response_or_new_file(
    response_text: str,
    *,
    generated_abs: Path,
    generated_preexisted: bool,
    generated_before: Optional[str],
    allow_existing_non_uta: bool = False,
) -> str:
    if generated_abs.exists():
        direct_body = generated_abs.read_text(encoding="utf-8", errors="replace")
        changed = not generated_preexisted or direct_body != (generated_before or "")
        if changed and looks_like_python_test(direct_body):
            if not allow_existing_non_uta and not is_uta_owned_test(direct_body):
                generated_abs.unlink()
            return direct_body
    return extract_python_test_body(response_text)


def looks_like_python_test(content: str) -> bool:
    return bool(
        re.search(
            r"^\s*(def|async\s+def)\s+test_",
            content or "",
            flags=re.MULTILINE,
        )
    )


def source_path_from_target_id(target_id: str) -> str:
    return source_path_from_target(target_id)


def module_name_from_source_path(repo: Path, source_path: str) -> str:
    return resolve_python_module(repo, source_path).module_name


__all__ = [
    "OWNERSHIP_MARKER",
    "extract_python_test_body",
    "generated_body_from_response_or_new_file",
    "is_uta_owned_test",
    "looks_like_python_test",
    "module_name_from_source_path",
    "render_generated_test_file",
    "source_path_from_target_id",
    "write_generated_test_file",
    "write_python_test_file",
]
